### PR TITLE
remove support firefox x86 on windows x86_64

### PR DESCRIPTION
**Pull request by vietngoc**
setup to run with firefox 64bit and notify upgrade when run with firefox 32 bit in windows x64

fixes https://github.com/mozilla/web-ext/issues/213

### CODE REVIEW

**Comment by kumar303** [comment]
@bwinton is this something you could review? I don't know enough about Windows.

**Comment by bwinton** [comment]
Probably…  I'll see if I get a chance to fire up my Windows VM this week.

**Comment by kumar303** [comment]
@bwinton thanks. I couldn't make it to mozlondon due to a family event -- sorry to miss everyone :(

**Comment by bwinton** [comment]
So, I've looked into it a bit, and determined that I either don't think it's doing the right thing, or I'm not familiar enough with Windows to understand what it is doing.  Maybe we can get one of the Firefox Windows developers to take a look?  Or someone who works with the installer, and might know where things we install end up?

**Comment by kumar303** [comment]
It also doesn't look right to me. @vietngoc could you add some details about the error you're trying to fix and how this patch fixes it?

**Comment by vietngoc** [comment]
Yes i am using firefox x64 and nodejs x64 in windows 10 x64. When i run web-ext, i receive notify error:
Running web extension from E:\Labs\test
Building web extension from E:\Labs\test
Your web extension is ready: C:\Users\xxx\AppData\Local\Temp\tmp-web-ext-4120GVW04J5ZfM39\test-1.0.xpi
Running Firefox with profile at C:\Users\xxx\AppData\Local\Temp\dcdc0135-aaa1-410d-8a8e-bead2534a8c4
Firefox error: Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
at exports._errnoException (util.js:870:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:437:9)
at process._tickCallback (node.js:351:17)
i am report bug in here: https://github.com/mozilla/web-ext/issues/213
in patch, i removed to check windows arch because in windows x64, firefox x64 installed in address C:\Program Files\ same as firefox x32 on windows x86 and notify upgrade when run with firefox 32 bit in windows x64

**Comment by kumar303** [comment]
oh, I forgot about your bug report (thanks for updating the PR with a link). Hmm, the original author who added the arch checks is not available to review this.

@bwinton does this break anything on other versions of Windows? There are two people with this problem in https://github.com/mozilla/web-ext/issues/213 so maybe we should just land it?

**Comment by bwinton** [comment]
So, I think using the 64-bit version of Firefox on 64-bit Windows is a good idea, but I think I'ld like to see a fallback to the 32-bit version of Firefox if the 64-bit version isn't installed (instead of the error this code currently gives).  Other than that, I'm pretty happy with it.  (Oh, also, all the tests fail on my VM, because my home directory has a space in it, but that seems like a different bug.)

**Comment by Croydon** [comment]
Actually, not supporting 64-bit is way worse than not supporting 32-bit FF, especially when 64-bit is becoming more and more default and reasons for 32-bit are vanishing step by step (e.g. NPAPI removal).

And to be clear about that once again. It only removes support for 32-bit FF on 64-bit Windows. So the people who are affected by that can definitely run the 64-bit edition.

Please continue with that patch.

PS: Since "Jetpack" will be killed of at the end of the year, maybe this repo should be moved to the Mozilla GitHub org so that it is easier to find it?

**Comment by kumar303** [comment]
> maybe this repo should be moved to the Mozilla GitHub org so that it is easier to find it?

Moving stuff is a hassle but we could do that.

Keep in mind that [web-ext](https://github.com/mozilla/web-ext) is the status quo for extension development it too uses `node-fx-runner`.

**Comment by yxliang01** [comment]
Hey guys, why conversation stopped?

**Comment by kumar303** [comment]
Believe it or not, 32-bit Firefox was still selected by *default* when you installed it on 64-bit Windows prior to Firefox 53. See https://bugzilla.mozilla.org/show_bug.cgi?id=797208

**Comment by vietngoc** [comment]
I recent add new requests in here. https://github.com/mozilla-jetpack/node-fx-runner/pull/30.

**Comment by yxliang01** [comment]
I prefer to detect all possible paths, I believe that's the best.

**Comment by kumar303** [comment]
A more minimal patch landed in https://github.com/mozilla-jetpack/node-fx-runner/pull/30

Thanks again @vietngoc

**Pull request closed without merging**
